# Generated by Django 5.0.7 on 2024-10-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0002_addevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='main_logo')),
            ],
        ),
    ]
