# Generated by Django 5.0.7 on 2024-09-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_customuser_membertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='membertype',
            field=models.CharField(max_length=100),
        ),
    ]
