# Generated by Django 5.0.7 on 2024-10-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customuser_city_customuser_gate_customuser_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='membertype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
